name: Garifix
description: "A new Flutter project connecting car owners with mechanics."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0  # Updated to match your current Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0  # HTTP package for making API calls
  font_awesome_flutter: ^10.4.0  # For using Font Awesome icons
  flutter_svg: ^1.0.3  # SVG support for Flutter
  cupertino_icons: ^1.0.8  # Default iOS icons package
  local_auth: ^2.1.3
  shared_preferences: ^2.0.0 # Check for the latest version
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0
  geolocator: ^9.0.0
  geocoding: ^2.1.0  # Add this line
  url_launcher: ^6.0.20  # Check for the latest version on pub.dev
  qr_flutter: ^4.0.0  # Or the latest version available
  mobile_scanner: ^4.0.0 # Add the version based on the latest one available
  fl_chart: ^0.40.0 # Check for the latest version
  awesome_dialog: ^3.0.0  # Update to the latest version compatible with your SDK
  simple_animations: ^5.0.0  # Check the latest compatible version
  socket_io_client: ^2.0.0
  intl: ^0.17.0
  lottie: ^1.2.2
  encrypt: ^5.0.0
  path: ^1.8.0
  flutter_rating_bar: ^4.0.0 # Add the latest version
  animate_do: ^2.0.0 # or the latest version
  animated_text_kit: ^4.2.1
  flutter_spinkit: ^5.1.0
  path_provider: ^2.0.12  # Use the latest version from pub.dev
  file_picker: ^5.2.5 # Use the latest version from pub.dev
  open_file: ^3.2.0
  fluttertoast: ^8.0.9  # Add this line
  pdf: ^3.6.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Linting for Flutter
  flutter_launcher_icons: ^0.9.2  # Add this line for icon generation
  


flutter:
  uses-material-design: true

  # Assets for the application, including the app logo
  assets:
    - assets/icons/google.svg
    - assets/icons/facebook.svg
    - assets/logo/app_logo.png  # Added the app logo here
    - assets/logo/app_logo1.png
    - assets/logo/account.jpg
    - assets/lotti/Animation - 1730958529727.json
    - assets/lotti/Animation - 1731569705908.json



flutter_icons:
  android: true  # To generate an icon for Android
  ios: true  # To generate an icon for iOS
  image_path: "assets/logo/app_logo.png"  # Path to the app logo image
