name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0  # Add this line
  font_awesome_flutter: ^10.4.0 # Or the latest version
  flutter_svg: ^1.0.3 # Check for the latest version

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add your assets section here
  assets:
    - assets/icons/google.svg
    - assets/icons/facebook.svg
