"""Add fingerprint_data column to user table

Revision ID: 230a89f1e2c9
Revises: 
Create Date: 2024-09-28 15:09:37.816500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230a89f1e2c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fingerprint_data', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('pin', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pin')
        batch_op.drop_column('fingerprint_data')

    # ### end Alembic commands ###
